services:
  - type: web
    name: todo-python-api
    runtime: python
    region: oregon
    plan: free
    buildCommand: cd python-backend && pip install -r requirements.txt
    startCommand: cd python-backend && uvicorn main:app --host 0.0.0.0 --port $PORT